#!/bin/sh /etc/rc.common

START=99
STOP=01

USE_PROCD=1
PROG=/usr/bin/rdp_controller.py

start_service() {
    procd_open_instance
    procd_set_param command python3 "$PROG"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file /etc/config/rdp_controller
    procd_close_instance
}

reload_service() {
    stop
    sleep 1
    start
}

service_triggers() {
    procd_add_reload_trigger "rdp_controller"
}
