#!/bin/sh /etc/rc.common

START=99
STOP=01

USE_PROCD=1
PROG=/usr/bin/rdp_controller.py

start_service() {
    local enabled
    config_get enabled main enabled 0

    if [ "$enabled" -eq 1 ]; then
        procd_open_instance
        procd_set_param command python3 $PROG
        procd_set_param respawn
        
        procd_set_param file /etc/config/rdp_controller
        procd_set_param file /etc/config/firewall
        
        procd_close_instance
    fi
}

stop_service() {
    true
}

reload_service() {
    stop
    sleep 1
    start
}

service_triggers() {
    procd_add_reload_trigger "rdp_controller"
    procd_add_reload_trigger "firewall"
}
